--when.repositories=["~/raven", "~/flock", "~/work/raven"]

[user]
email = "mathew.harman@flocksafety.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "~/.config/git/allowed_signers"
