--when.repositories=[
    "~/work/zephyr-tracker-root",
    "~/m2md/zephyr-tracker-root",
    "~/work/esp-wifi-scan",
    "~/m2md/esp-wifi-scan",
    "~/work/monorepo",
    "~/m2md/monorepo",
]

[user]
email = "Mathew.Harman@m2mdtech.com"

[signing]
key = "D28DC6534B501C81"
